apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - target:
      kind: Ingress
      name: forge-mi-ingress-base-static
    path: ./patches/ingress.yaml